version: '3.1'

services:

  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: pwpostgres
      
  iamcentral:
    image: jboss/keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_FRONTEND_URL: https://${DEVENV_SERVERNAME}:8443/iamcentral/auth
      PROXY_ADDRESS_FORWARDING: 'true'
      DB_VENDOR: postgres
      DB_ADDR: db
      DB_PORT: 5432
      DB_DATABASE: postgres
      DB_SCHEMA: iamcentral
      DB_USER: kccentral
      DB_PASSWORD: pwkccentral
      X509_CA_BUNDLE: /tmp/ca/devenv-ca.crt
      KEYCLOAK_IMPORT: /tmp/realm-export.json
    volumes:
      - ./keycloak/iamcentral/realm-export.json:/tmp/realm-export.json
      - ./keycloak/ca:/tmp/ca
    extra_hosts:
      - "${DEVENV_SERVERNAME}:${DEVENV_IP}"

  iamshared:
    image: jboss/keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_FRONTEND_URL: https://${DEVENV_SERVERNAME}:8443/iamshared/auth
      PROXY_ADDRESS_FORWARDING: 'true'
      DB_VENDOR: postgres
      DB_ADDR: db
      DB_PORT: 5432
      DB_DATABASE: postgres
      DB_SCHEMA: iamshared
      DB_USER: kcshared
      DB_PASSWORD: pwkcshared
      X509_CA_BUNDLE: /tmp/ca/devenv-ca.crt
      KEYCLOAK_IMPORT: /tmp/realm-export.json
    volumes:
      - ./keycloak/iamshared/realm-export.json:/tmp/realm-export.json
      - ./keycloak/ca:/tmp/ca
    extra_hosts:
      - "${DEVENV_SERVERNAME}:${DEVENV_IP}"

  ingress:
    image: nginx
    ports:
      - 8443:443
    volumes:
      - ./nginx/conf/:/etc/nginx/
      - ./nginx/certs/:/etc/ssl/certs/

