version: '3.1'

services:

  db:
    image: postgres:14.5
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: pwpostgres
      
  iamcentral:
    image: keycloak/keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME_URL: https://${DEVENV_SERVERNAME}:8443/iamcentral/auth
      KC_HOSTNAME_ADMIN_URL: https://${DEVENV_SERVERNAME}:8443/iamcentral/auth
      KC_HOSTNAME_STRICT_BACKCHANNEL: "true"
      KC_HTTP_RELATIVE_PATH: auth
      KC_PROXY_HEADERS: xforwarded
      KC_DB: postgres
      KC_DB_URL_HOST: db
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: postgres
      KC_DB_SCHEMA: iamcentral
      KC_DB_USERNAME: kccentral
      KC_DB_PASSWORD: pwkccentral
      X509_CA_BUNDLE: /tmp/ca/devenv-ca.crt
    command: start-dev
    volumes:
      - ./keycloak/ca:/tmp/ca
    extra_hosts:
      - "${DEVENV_SERVERNAME}:${DEVENV_IP}"

  iamshared:
    image: keycloak/keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME_URL: https://${DEVENV_SERVERNAME}:8443/iamshared/auth
      KC_HOSTNAME_ADMIN_URL: https://${DEVENV_SERVERNAME}:8443/iamshared/auth
      KC_HOSTNAME_STRICT_BACKCHANNEL: "true"
      KC_HTTP_RELATIVE_PATH: auth
      KC_PROXY_HEADERS: xforwarded
      KC_DB: postgres
      KC_DB_URL_HOST: db
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: postgres
      KC_DB_SCHEMA: iamshared
      KC_DB_USERNAME: kcshared
      KC_DB_PASSWORD: pwkcshared
      X509_CA_BUNDLE: /tmp/ca/devenv-ca.crt
    command: start-dev
    volumes:
      - ./keycloak/ca:/tmp/ca
    extra_hosts:
      - "${DEVENV_SERVERNAME}:${DEVENV_IP}"

  ingress:
    image: nginx
    ports:
      - 8443:443
    volumes:
      - ./nginx/conf/:/etc/nginx/
      - ./nginx/certs/:/etc/ssl/certs/

