version: '3.1'

services:

  db:
    image: postgres:14.5
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: pwpostgres
      

