# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: pwpostgres
      
  iamcentral:
    image: jboss/keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: postgres
      DB_ADDR: devenv_db
      DB_PORT: 5432
      DB_DATABASE: postgres
      DB_SCHEMA: iamcentral
      DB_USER: kccentral
      DB_PASSWORD: pwkccentral
      KEYCLOAK_IMPORT: /tmp/realm-export.json
    ports:
      - 8080:8080
      - 8443:8443
    volumes:
      - ./keycloak/iamcentral/realm-export.json:/tmp/realm-export.json

  iamshared:
    image: jboss/keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: postgres
      DB_ADDR: devenv_db
      DB_PORT: 5432
      DB_DATABASE: postgres
      DB_SCHEMA: iamshared
      DB_USER: kcshared
      DB_PASSWORD: pwkcshared
      KEYCLOAK_IMPORT: /tmp/realm-export.json
    ports:
      - 8081:8080
      - 8444:8443
    volumes:
      - ./keycloak/iamshared/realm-export.json:/tmp/realm-export.json

